GET http://localhost:8080/api/posts

###
GET http://localhost:8080/api/posts
X-Api-Version: 1.0

###
GET http://localhost:8080/api/posts
X-Api-Version: 2.0

###
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "my post title 1",
  "body": "my post body 1",
  "userId": 1
}